### PR TITLE
Updated duck.sh

### PR DESCRIPTION
**Pull request by chriscn**
Log message includes the domains, so you can know that they've updated succesfully.

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-duckdns/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Logging message now includes the subdomains.

### CODE REVIEW

**Comment by tobbenb** [comment]
I don't see how adding the subdomain to the message will change anything. The current message says the IP was updated.

Also, the message you changed to doesn't read right. Shouldn't there be a "for" before $SUBDOMAIN?

**Comment by chriscn** [comment]
> I don't see how adding the subdomain to the message will change anything. The current message says the IP was updated.

I have multiple DuckDNS subdomains hosted at different locations; it would be easier to just check a log file to check that it had updated it. Maybe I should loop over each of the subdomains and perform a seperate request to see if it has been succesful?

**Comment by aptalca** [comment]
Honestly, this doesn't add much benefit, and might break any checks users may have set up (like healthchecks) parsing the log messages.

>I have multiple DuckDNS subdomains hosted at different locations; it would be easier to just check a log file to check that it had updated it. Maybe I should loop over each of the subdomains and perform a seperate request to see if it has been succesful?

That means you are running separate containers in different locations and check them separately? It should be easy to know which log you're checking based on which host you're connecting to, no? Unless I'm missing something.

**Comment by chriscn** [comment]
I hadn't thought about users breaking health checks, for the slight benefit for me it could cause a lot of issues. I will close this PR.

**Pull request closed without merging**
