### PR TITLE
Update 40-config grammar correction

### PR DESCRIPTION
**Pull request by cybrnook**
Correct the grammar used when specifying the where the log output will be written to. As well, combined two sentences into one to avoid a fragment.

Signed-off-by: Hans Geiblinger <cybrnook2002@yahoo.com>

### CODE REVIEW

**Comment by aptalca** [comment]
Output is also a verb and its use here is grammatically correct: https://www.merriam-webster.com/dictionary/output

**Comment by cybrnook** [comment]
Then in your case you should change it to "outputted" since that would be the correct use.

**Comment by aptalca** [comment]
Past tense of output is output or outputted. You are dangerously close to troll territory. I suggest you stop now.

**Comment by cybrnook** [comment]
Troll? I am just trying to help, hence taking time to make the PR. Anyways, we don't agree so I am moving on, no offense on your side was meant.

**Pull request closed without merging**
