### PR TITLE
Add support for updating IPv6

### PR DESCRIPTION
**Pull request by eljojo**
Hello,
In this PR I'm trying to add IPv6 support to the image.

The biggest challenge I had was:
- how to obtain the ipv6, since we cannot just pass `ipv6=` and expect duckdns to fetch it automatically
- avoid a second request to duckdns, it seems that `ip=&ipv6=[actual_ipv6]` ends up only setting the IPv6 leaving the IPv4 untouched.

I'm unsure whether this is the right approach, but I couldn't find a way of making fewer HTTP requests.

I'm very open to suggestions. I'm not really good at bash.

@sparklyballs @aptalca

### CODE REVIEW

**Comment by eljojo** [comment]
As I put this into "production" I kinda just realised it might not make so much sense, since no one really NATs IPv6.

**Comment by homerr** [comment]
@eljojo do you want to close this off then or is it worth including? You've done the dirty and put it into production so... how's it work ;)

**Comment by eljojo** [comment]
Let's close it. I don't think it makes sense.

**Comment by toobie83** [comment]
My internet connection and I think a lot of other here in germany also changed to DS-Lite - so full ipv6.
Is there any way to add this to duckdns?

**Comment by deranjer** [comment]
@toobie83 It would be odd if your provider was issuing you dynamic ipv6 addresses, they should give you a /64 block or something similar that shouldn't change.

**Pull request closed without merging**
